version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/tododb
    networks:
      - todo-net

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - todo-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - todo-net

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.16
    ports:
      - "5044:5044"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - todo-net

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.16
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
